# Use UTF-8 for Korean input and other multibyte characters.
export LANG=C.UTF-8
export LC_CTYPE=C.UTF-8
if [[ -n ${LC_ALL-} ]]; then
  export LC_ALL=C.UTF-8
fi
setopt multibyte

# Oh My Zsh setup.

export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME=""

# Ansible manages the Oh My Zsh revision.
zstyle ':omz:update' mode disabled

plugins=(
  git
)

export HISTFILE="$HOME/.zsh_history"
export HISTSIZE=10000
export SAVEHIST=10000

setopt append_history
setopt share_history
setopt hist_ignore_dups
setopt hist_ignore_space
setopt auto_cd
setopt correct
setopt prompt_subst

zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

source "$ZSH/oh-my-zsh.sh"

if [ -f /usr/share/doc/fzf/examples/key-bindings.zsh ]; then
  source /usr/share/doc/fzf/examples/key-bindings.zsh 2>/dev/null
fi

if [ -f /usr/share/doc/fzf/examples/completion.zsh ]; then
  source /usr/share/doc/fzf/examples/completion.zsh 2>/dev/null
fi

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias grep='grep --color=auto'
alias ..='cd ..'
alias ...='cd ../..'
alias sc='systemctl'

if [ -f /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh ]; then
  source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
fi

if [ -f /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]; then
  source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi

eval "$(starship init zsh)"
